import os

API_PORT = os.getenv("API_PORT")
USERS_SERVICE_HOST = os.getenv("USERS_SERVICE_HOST")
QUESTIONS_SERVICE_HOST = os.getenv("QUESTIONS_SERVICE_HOST")
SESSIONS_SERVICE_HOST = os.getenv("SESSIONS_SERVICE_HOST")
MATCHING_SERVICE_HOST = os.getenv("MATCHING_SERVICE_HOST")